### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by Symon-S** [manuelVo/foundryvtt-rangefinder#1]
Changed activation key to ControlLeft.
Every time key is pressed this error is displayed, but rangefinder still seems to work.
Uncaught TypeError: Cannot read property 'ctrlKey' of null
    at settings-extender.js:90
    at Array.reduce (<anonymous>)
    at modifiersEqual (settings-extender.js:89)
    at eventIsForBinding (settings-extender.js:98)
    at Function.KeyBinding.eventIsForBinding (settings-extender.js:212)
    at window.addEventListener.useCapture (layer-hotkeys.js:88)

**Comment by manuelVo** [comment]
I think this might be a conflict with the settings extender module. Can you please check if the error goes away if you disable the SettingsExtender module?

**Comment by Symon-S** [comment]
Don't have a SettingsExtender module installed

**Comment by manuelVo** [comment]
In that case it's probably a conflict with a module that uses settings extender as a library. Narrow down which module the conflicting one may be (for example by using the "Find the Culprit" module)?

**Comment by Symon-S** [comment]
This problem is no longer occuring for me
