### ISSUE TITLE
Potential conflict with Easy Target module

### ISSUE THREAD

**Issue by dirusulixes** [manuelVo/foundryvtt-rangefinder#3]
libWrapper reports
```Potential conflict detected between module 'rangefinder' and 'easy-target'.
Detected non-libWrapper wrapping of 'Canvas.prototype._onClickLeft' by 'rangefinder'.

```
  | 🎁console_ui | @ | libWrapper-notifications.js:64
-- | -- | -- | --
  | 🎁conflict | @ | libWrapper-notifications.js:83
  | 🎁warn_classic_wrapper | @ | libWrapper-wrapper.js:708
  | 🎁set_nonproperty | @ | libWrapper-wrapper.js:686
  | 🎁Canvas.prototype._onClickLeft#setter | @ | libWrapper-wrapper.js:294
  | hookFunctions | @ | main.js:37
  | (anonymous) | @ | main.js:3
  | Hooks._call#hook=init | @ | libWrapper-errors.js:190
  | _call | @ | foundry.js:2496
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:441
  | 🎁Hooks._call#lib-wrapper | @ | libWrapper-errors.js:205
  | 🎁Hooks._call#0 | @ | libWrapper-wrapper.js:142
  | callAll | @ | foundry.js:2456
  | initialize | @ | foundry.js:6457
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:441
  | 🎁libWrapperInit | @ | libWrapper-api.js:507
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:142
  | window.addEventListener.once | @ | foundry.js:7449
  | async function (async) |   |  
  | window.addEventListener.once | @ | foundry.js:7448

**Comment by manuelVo** [comment]
This warning merely tells you that Rangefinder isn't utilizing the libwrapper and that it isn't able to determine whether there might be a conflict as a result. Is one of the two modules actually breaking?

**Comment by dirusulixes** [comment]
Good point. I've tested it a bit, and so far I cannot see any breakage.

**Comment by manuelVo** [comment]
In that case I'll close this issue for the time being. Should you encounter any incompatibilities feel free to open a new issue :)
