### ISSUE TITLE
Please consider updating for v10

### ISSUE THREAD

**Issue by LukasPrism** [manuelVo/foundryvtt-rangefinder#5]
Hi there

This has to be one of our most used modules, and we were disappointed to find that it's not working in v10 now that we've upgraded our game. Is there going to be a v10 release?

Failing that, possibly a keybind in drag ruler that does the same thing? We also use that, of course!

Many thanks from a huge fan.

**Comment by manuelVo** [comment]
While the module is not explicitly tagged for v10 compatibility, it's working fine on my installation. Please try disabling all other modules to see if there are any possible conflicting modules. Checking the keybindings for conflicts with the rangefinder binding might be helpful too.

**Comment by LukasPrism** [comment]
Ah, thank you! I'll install via the manifest link then and report back if any issues.
